### ISSUE TITLE
Add tooltips to menu-options in editors.

### ISSUE THREAD

**Issue by artus** [Graphite-Docs/graphite#10]
The purpose of some of the option of the menus in the editors is not clear. Adding tooltips when hovering over a certain button would greatly improve user-friendliness.

![image](https://user-images.githubusercontent.com/22665347/38615434-f1ac329a-3d90-11e8-943e-be61658323db.png)

**Comment by jehunter5811** [comment]
@artusvranken Thanks! Converting this to a feature request. Totally agree, though.

**Comment by jehunter5811** [comment]
Very delayed on this, but this was added with the release of the new Docs editor.
