### ISSUE TITLE
Unable to upload html file

### ISSUE THREAD

**Issue by friedger** [Graphite-Docs/graphite#111]
When I upload a image to the vault all is fine.
When I upload an html file the file is not uploaded:

`TypeError: Argument 1 of FileReader.readAsDataURL is not an object.[Learn More] main.2a7dca95.js:643:177791
	t.a https://app.graphitedocs.com/static/js/main.2a7dca95.js:643:177791
	<anonymous> self-hosted:978:17
	value https://app.graphitedocs.com/static/js/main.2a7dca95.js:636:1193836
	value self-hosted:974:17
	invokeGuardedCallback/< https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:682
	invokeGuardedCallback https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:557
	invokeGuardedCallbackAndCatchFirstError https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:842
	x https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:2320
	P https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:2801
	M https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:2958
	N https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:2607
	F https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:3563
	L https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:3719
	xn https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:30945
	Zo https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:85600
	Je https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:12584
	Mn https://app.graphitedocs.com/static/js/main.2a7dca95.js:119:31493
	Mn self-hosted:1018:17
`

**Comment by jehunter5811** [comment]
@friedger This is an oversight in that it even let you pick an HTML file. However, Vault should absolutely support HTML files, so I'll work on a fix for that.

**Comment by jehunter5811** [comment]
@friedger I finally got around to this and it should be available in the next release! I'll post here when it's available.

**Comment by jehunter5811** [comment]
@friedger This is now supported!
