### ISSUE TITLE
Shoddy loading on shared documents

### ISSUE THREAD

**Issue by bryanwillis7** [Graphite-Docs/graphite#117]
A fairly consistent issue I'm seeing is that my shared documents simply aren't loading when people click the public link. Sometimes if I mash the page reload button a few times I can get the document loaded. But otherwise it's fairly unreliable. I've tried on mobile and on desktop and it's always a bit unreliable.

**Comment by bryanwillis7** [comment]
https://app.graphitedocs.com/shared/docs/forleafe.id.blockstack-1542140230230

This document failed to load twice on someone else's computer. But on my own it managed to load after a few refreshes.

**Comment by bryanwillis7** [comment]
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fapp.graphitedocs.com%2Fshared%2Fdocs%2Fforleafe.id.blockstack-1542140230230
Here's a failed speed test as proof.
![failed](https://user-images.githubusercontent.com/17366653/48487632-ca789b80-e7ec-11e8-8d3e-913ec4a4bd30.png)

**Comment by jehunter5811** [comment]
Thanks! Probably going to need more details about what the common denominator is between your machine and the people you are sharing with. I just tested that link (in a private window for each browser to make sure nothing was previously cached) in the following browsers: 

Brave: 3 seconds to load
Chrome: 6 seconds to load
Firefox: 6 seconds to load

Can you tell me what OS you're using and what browser you and anyone else you've shared it with might be using? Additionally, can you open the developer console and take a screenshot of any errors?

I'd also say the Google Page Speed insights tool is far from accurate. Using their own built-in browser tools gives you completely different results: 

<img width="1143" alt="screen shot 2018-11-14 at 9 00 35 am" src="https://user-images.githubusercontent.com/10519834/48490919-1119c600-e7ec-11e8-8c45-bac7e9f59b43.png">

19.1 seconds on Google Page Speed Insights. 8 seconds in the developer tools. 6 seconds when I timed it myself. 

If it's not loading at all for your and the people you shared with, then something else is going on that I want to help track down!

**Comment by bryanwillis7** [comment]
One device was an android smartphone running Firefox Mobile. Another device was a linux desktop running firefox, another was a desktop running windows 7 and chrome.

I'm going to have to try those devices again and check the results of the desktop versions. But I just refreshed my android running firefox and the page loaded after about 6 seconds. 

Again, it's kind of inconsistent. Up until this point I couldn't get it to load at all, but now on my phone it's loading after 6 seconds.

**Comment by jehunter5811** [comment]
When it doesn't load again, can you open the developer console and take a screenshot of anything in there? I want to make sure this works every time for you.

**Comment by bryanwillis7** [comment]
Will do, I'll let you know as soon as it happens again.
