### ISSUE TITLE
Weird glitches. Hitting backspace after working on a document for a while causes page to jump

### ISSUE THREAD

**Issue by bryanwillis7** [Graphite-Docs/graphite#125]
I've tested this bug on a few different computers. After a while Graphite will jump to the bottom of the page any time the backspace key is hit, or if basically any of the toolbar options are clicked. I took a look at the console to see if it was throwing any errors, and all I found was this:

![moreerros](https://user-images.githubusercontent.com/17366653/48729531-ce9a2400-ec05-11e8-8bed-a01b112bdaa0.png)

I don't know if these errors are at all related to the bug, or a separate issue entirely.

**Comment by jehunter5811** [comment]
Those errors are unrelated to the problem you're seeing. Does the issue happen after a certain amount of text is input or does it happen always?

**Comment by bryanwillis7** [comment]
I've looked into it a bit more and it appears to be after a certain amount of text. I tried deleting a paragraph and the behavior temporarily stopped. When I put the paragraph back in it started back up.

**Comment by jehunter5811** [comment]
This may very well be the underlying open source editor Graphite uses and customizes. I'm looking into it further. Here's one of the issues I found from that codebase that might be causing this: https://github.com/quilljs/quill/issues/2197

I'll continue exploring ways Graphite can mitigate this.

**Comment by jehunter5811** [comment]
Oh man, I just added a 50k word document to test this one and it's a nightmare. Good catch! If the underlying editor can't support that amount of text, Graphite's going to go with a different solution.

**Comment by bryanwillis7** [comment]
I'm glad I could be of some help in pointing these things out. I want as much as I can to support the open internet and see to it that solid projects like this are integrated into my daily workflow.

It's a shame that Quill hasn't fixed that crippling problem with their software. It's seems like it's so well put together otherwise.

**Comment by jehunter5811** [comment]
Looks like Slate.js has some optimization for large documents. 

https://www.slatejs.org/#/huge-document

I'll be exploring that. I really appreciate you banging on Graphite so much. It's good to catch some of the more common use cases as well as the edge cases.

**Comment by jehunter5811** [comment]
@bryanwillis7 the new editor is released! It should support these large documents much much better. Closing this issue now.
