### ISSUE TITLE
Formulas/functions in sheets?

### ISSUE THREAD

**Issue by slgraham** [Graphite-Docs/graphite#13]
Are formulas possible in Sheets? I don't see any option to create one, but I might be missing something...

**Comment by jehunter5811** [comment]
Hi @slgraham, Yes, there was formula support. It has been temporarily disabled as we evaluate the speadsheets component's use case within the app as a whole. Would love to hear your overall thoughts on spreadsheets within Graphite.

**Comment by slgraham** [comment]
My initial use case would be to move my personal budgeting spreadsheets over to graphite from google. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jehunter5811** [comment]
Formula support will soon return! Look for an announcement soon. Will close this issue once that support is restored.

**Comment by jehunter5811** [comment]
https://medium.com/the-lead/pushing-the-limits-of-decentralized-spreadsheets-21ddb21af464

**Comment by jehunter5811** [comment]
Formula support is back! Documentation coming, but since formulas are back, I'm going to close this issue.
