### ISSUE TITLE
Silently fails to save sheet

### ISSUE THREAD

**Issue by jbeard4** [Graphite-Docs/graphite#131]
<img src="http://g.recordit.co/UUvFigzTxE.gif">

**Comment by jbeard4** [comment]
This is probably because Brave is blocking a cookie under Shields Up mode. Still, it probably shouldn't silently fail.

**Comment by jehunter5811** [comment]
This is definitely tied to Brave. I've seen this same behavior if I don't turn off some of the blockers. I need to investigate why Brave is blocking network activity by default on all Blockstack apps.

**Comment by jehunter5811** [comment]
Looks like I do have a catch in Docs. Just need to add a catch in Sheets as well. But that's still a terrible experience. I'd rather figure out why these post requests are automatically blocked by Brave.

**Comment by jehunter5811** [comment]
Unfortunately, this is something Brave is going to need to fix. They have a bug open for it, but it's a pretty widespread issue. Closing since there's nothing Graphite can do to resolve the actual saving issue.
