### ISSUE TITLE
Bug: upload image not work now

### ISSUE THREAD

**Issue by gitkiwikiwi** [Graphite-Docs/graphite#133]
I remember old version can upload local images.

**Comment by jehunter5811** [comment]
Thanks for reporting this and sorry for the delay in responding. We were building out the new editor that I knew would fix this so I was holding off on a response. The new editor is officially released. You can now upload images as normal or select images from Graphite Vault.

**Comment by gitkiwikiwi** [comment]
uploading images feature fixed, thanks,and more point,I tried the share
publicly, but it always in only readable status ,seems editable not work.

Justin Hunter <notifications@github.com> 于2018年12月21日周五 下午11:36写道：

**Comment by jehunter5811** [comment]
Hmm let’s open a separate issue for this. Do you mind doing that?

**Comment by gitkiwikiwi** [comment]
I submitted an issue.

Justin Hunter <notifications@github.com> 于2018年12月23日周日 上午12:56写道：
