### ISSUE TITLE
I met errors when I tried to install it on local computer.

### ISSUE THREAD

**Issue by gitkiwikiwi** [Graphite-Docs/graphite#136]
I followed the tutorial ,and git clone to local, then typed command as follows:

$ cd graphite
kiwikiMacBook-Pro:graphite gitkiwi$ cd web
kiwikiMacBook-Pro:web gitkiwi$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN @handsontable-pro/react@1.1.0 requires a peer of handsontable-pro@^5.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-immutable-proptypes@2.1.0 requires a peer of immutable@>=3.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN slate@0.44.8 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-deep-table@0.8.0 requires a peer of slate@0.43.x but none is installed. You must install peer dependencies yourself.
npm WARN slate-edit-code@0.15.5 requires a peer of immutable@^3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-edit-code@0.15.5 requires a peer of slate@^0.33.0 but none is installed. You must install peer dependencies yourself.
npm WARN slate-edit-code@0.15.5 requires a peer of slate-react@^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN slate-html-serializer@0.7.32 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-plain-serializer@0.6.32 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-prop-types@0.5.23 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-react@0.21.14 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN transit-immutable-js@0.7.0 requires a peer of immutable@>= 3 but none is installed. You must install peer dependencies yourself.

added 2 packages from 2 contributors in 108.729s
npm ERR! Object.entries is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/gitkiwi/.npm/_logs/2018-12-22T06_37_29_463Z-debug.log

**Comment by jehunter5811** [comment]
This appears to be an NPM issue. Looks like your instance of npm might be out of date. Can you try updating to the most recent version of npm then run the commands again?

**Comment by gitkiwikiwi** [comment]
@jehunter5811    I upgraded  npm to 6.5.0 ,deleted old graphite folder and typed command as follows:

git clone https://github.com/Graphite-Docs/graphite.git

cd graphite
cd web
npm install
npm run start
but errors show again:

npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN @handsontable-pro/react@1.1.0 requires a peer of handsontable-pro@^5.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-immutable-proptypes@2.1.0 requires a peer of immutable@>=3.6.2 but none is installed. You must install peer dependencies yourself.
npm WARN slate@0.44.8 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-deep-table@0.8.0 requires a peer of slate@0.43.x but none is installed. You must install peer dependencies yourself.
npm WARN slate-edit-code@0.15.5 requires a peer of immutable@^3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-edit-code@0.15.5 requires a peer of slate@^0.33.0 but none is installed. You must install peer dependencies yourself.
npm WARN slate-edit-code@0.15.5 requires a peer of slate-react@^0.12.0 but none is installed. You must install peer dependencies yourself.
npm WARN slate-html-serializer@0.7.32 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-plain-serializer@0.6.32 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-prop-types@0.5.23 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN slate-react@0.21.14 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN transit-immutable-js@0.7.0 requires a peer of immutable@>= 3 but none is installed. You must install peer dependencies yourself.

added 2 packages from 2 contributors, moved 3 packages and audited 36471 packages in 112.7s
found 120 vulnerabilities (47 low, 54 moderate, 18 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details


localhost:3000 page shows:

Failed to compile
./src/components/helpers/keys.js
Module not found: Can't resolve './dev' in '/Users/sulayman/graphite/web/src/components/helpers'


As prompts  said, I executed npm audit fix  command. and show results as follows:

npm WARN slate-react@0.21.14 requires a peer of immutable@>=3.8.1 but none is installed. You must install peer dependencies yourself.
npm WARN transit-immutable-js@0.7.0 requires a peer of immutable@>= 3 but none is installed. You must install peer dependencies yourself.

+ request@2.88.0
+ mammoth@1.4.7
added 29 packages from 47 contributors, removed 96 packages and updated 34 packages in 135.551s
fixed 95 of 120 vulnerabilities in 36471 scanned packages
  4 vulnerabilities required manual review and could not be updated
  2 package updates for 21 vulns involved breaking changes
  (use `npm audit fix --force` to install breaking changes; or refer to `npm audit` for steps to fix these manually)

**Comment by jhunter5811** [comment]
Looks like you're not running into install errors (the warning are fine). You are now hitting the issue that's documented here in the README. 

https://github.com/Graphite-Docs/graphite#install

Follow the steps there and you should be fine.

**Comment by gitkiwikiwi** [comment]
I totally installed it by the README, but I cannot install it successfully.
same steps as the tutorial.

jhunter5811 <notifications@github.com> 于2018年12月30日周日 上午9:15写道：
