### ISSUE TITLE
bug:seems editable  feature not work.

### ISSUE THREAD

**Issue by gitkiwikiwi** [Graphite-Docs/graphite#140]
I tried to click the share publicly button , but it always in only readable status,seems editable feature not work.

**Comment by jhunter5811** [comment]
Can you send me an example public link? I've tested this multiple times and make editable works for me.

**Comment by gitkiwikiwi** [comment]
I remember  after I clicked "public link" ,it would generated an url
address, but the new edit shows only two button that make editable and stop
sharing publicly without url address below them.
Here is the url address on the browser.
https://app.graphitedocs.com/documents/doc/1544809252084

jhunter5811 <notifications@github.com> 于2018年12月30日周日 上午9:20写道：

**Comment by jehunter5811** [comment]
I'm not sure I'm following. That link is the link to your private document. When you click Share Publicly, you'll get a modal that gives you the option to make the document editable or stop sharing. There will be a public link under those buttons. If you don't see that for some reason, click the stop sharing button, then share it again.

**Comment by jehunter5811** [comment]
Closing since there has not been any activity since Jan.
