### ISSUE TITLE
Sign Up button in the site is not working.

### ISSUE THREAD

**Issue by chalcosoma** [Graphite-Docs/graphite#152]
Sign Up button in the site is not working.

Environment:
Fedora 29 x64, GNOME 3.30.2, Firefox x64 65.0.

Steps to reproduce:
Go to https://www.graphitedocs.com/ > Sign Up.
In the new tab (https://app.graphitedocs.com/) click on Sign Up.

Expected Result:
See an interface to create account.

Actual Result:
Nothing happens.

**Comment by camronlevanger** [comment]
Can confirm. You can't sign in, or sign up using Firefox on Ubuntu or MacOS. Seems to be working fine from Chrome and Chromium.

**Comment by jehunter5811** [comment]
Hi Camron! Thanks for the report. This is a known problem with Blockstack. They should have a solution soon, but until then, you will need to download the Blockstack Browser if you want to use Firefox. You can do so here: 

https://blockstack.org/install

**Comment by jehunter5811** [comment]
This was resolved with the update to blockstack.js 18.3.0
