### ISSUE TITLE
Sign in button links to non-https site

### ISSUE THREAD

**Issue by larrysalibra** [Graphite-Docs/graphite#153]
The "sign in" link on https://www.graphitedocs.com points to non-https version of the graphite app. This is a potential security issue and makes the link fail if a browser only supports secure https sites.

See screenshot:

<img width="841" alt="screen shot 2019-02-06 at 11 34 12 pm" src="https://user-images.githubusercontent.com/597182/52352540-bbaa2980-2a67-11e9-8d5a-f261c995ed72.png">

**Comment by jehunter5811** [comment]
Thanks, Larry! I’ll fix this during the. Ext marketing site update.

**Comment by jehunter5811** [comment]
Resolved in the most recent marketing site push.
