### ISSUE TITLE
【performance issues】webpages loading time is  really too long to reload the documents from server

### ISSUE THREAD

**Issue by gitkiwikiwi** [Graphite-Docs/graphite#155]
from the developer console ,every time,  I found if I  reload the document page, It would spent about 15.49s to reload all docs, it's too long to wait !!!! but the file size only 83kb. the NO.2 reload file link is https://whispering-sands-47101.herokuapp.com/socket.io/?EIO=3&transport=polling&t=Mbc7qmt&sid=PtriMOPPkmUDvs87AAAf, other css and js files are  no more than 1 s , but they are  all on external servers.So,Are the graphite server (vps) and cdn cause the performance issues? I recommend cloudflare and linode, it's good for global users. And I don't know why graphite choose Netlify CDN and as web server. Why not nginx and openresty? May be  it's not the vps and cdn issues.

These are the file links need to be fixed:

- https://whispering-sands-47101.herokuapp.com/socket.io/?EIO=3&transport=polling&t=Mbc7pyv

- https://whispering-sands-47101.herokuapp.com/socket.io/?EIO=3&transport=polling&t=Mbc7q8z

- https://whispering-sands-47101.herokuapp.com/socket.io/?EIO=3&transport=polling&t=Mbc7qlB&sid=amvLRCnNYr6q_M6jAAAe

**Comment by jehunter5811** [comment]
Thanks for this detailed report. The server links you referred to are specifically for real-time collaboration. If the documents in question have not been shared with someone else (with real-time collaboration enabled), the polling should not be happening. Can you confirm whether you are seeing polling to those websocket server links on documents that have not been shared?

Also, would it be too much trouble to do a screen recording of the loading time troubles you're seeing?

**Comment by jehunter5811** [comment]
@gitkiwikiwi I just pushed out an update that should prevent the websockets server from being polled unless a document is either shared publicly with real-time collaboration enabled or shared with a contact with real-time collaboration enabled. Hopefully this helps the performance issues you were seeing. 

I'm going to run some other performance tests as well.

**Comment by jehunter5811** [comment]
Closing unless additional information is provided from after the most recent releases.
