### ISSUE TITLE
Local development

### ISSUE THREAD

**Issue by human94** [Graphite-Docs/graphite#164]
Dear Community, 
As I'm relatively new to Blockstack and have limited coding knowledge, I was looking for help. I wanted to clone the repo of Graphite and play around with the UI. However, after cloning the repo and running it on my terminal and signing in, I only see the attached screenshot as the interface. May this be related to **browserify requires.js -o public/bundle.js** ?

Correct me if I'm wrong but I was expecting the graphite interface I'd see when signing in through blockstack itself or graphite.com. Any help or clarification would be kindly appreciated. 

<img width="1436" alt="Bildschirmfoto 2019-05-27 um 13 37 51" src="https://user-images.githubusercontent.com/50052641/58417308-b0195780-8084-11e9-9ef5-449fade47760.png">

**Comment by jehunter5811** [comment]
This is not part of the graphite repository. The error is surely tied to the repository you cloned.
