### ISSUE TITLE
bug: npm errors when I tried to compiles files on my local computer

### ISSUE THREAD

**Issue by gitkiwikiwi** [Graphite-Docs/graphite#166]
**I followed these steps :**

`
git clone https://github.com/Graphite-Docs/graphite.git
cd graphite
npm install
`

**results I got:**

npm WARN saveError ENOENT: no such file or directory, open '/Users/coder/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/coder/package.json'
npm WARN coder No description
npm WARN coder No repository field.
npm WARN coder No README data
npm WARN coder No license field.
up to date in 5.127s
found 0 vulnerabilities

**every thing seems fine but when I run command:**

npm run start

errors began show up:

npm ERR! path /Users/coder/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/coder/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/coder/.npm/_logs/2019-06-08T04_41_43_215Z-debug.log
sulaymantekiMacBook-Pro:graphite coder$ npm start
npm ERR! path /Users/coder/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/Users/coder/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/coder/.npm/_logs/2019-06-08T04_42_31_081Z-debug.log

**and I found the log file,These are the contents inside:**

0 info it worked if it ends with ok
1 verbose cli [ '/Users/coder/.nvm/versions/node/v10.15.0/bin/node',
1 verbose cli   '/Users/coder/.nvm/versions/node/v10.15.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v10.15.0
4 verbose config Skipping project config: /Users/coder/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/Users/coder/package.json'
6 verbose cwd /Users/coder/graphite
7 verbose Darwin 18.6.0
8 verbose argv "/Users/coder/.nvm/versions/node/v10.15.0/bin/node" "/Users/coder/.nvm/versions/node/v10.15.0/bin/npm" "start"
9 verbose node v10.15.0
10 verbose npm  v6.4.1
11 error path /Users/coder/package.json
12 error code ENOENT
13 error errno -2
14 error syscall open
15 error enoent ENOENT: no such file or directory, open '/Users/coder/package.json'
16 error enoent This is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**How to fix it?**

**Comment by jehunter5811** [comment]
Need to update the README. Sorry about that. `cd client` then run `npm install`.
