### ISSUE TITLE
Failed to fetch information about the app requesting authentication

### ISSUE THREAD

**Issue by mkvaghani** [Graphite-Docs/graphite#167]
While trying to authenticate Blockstack, getting an error. 

Failed to fetch information about the app requesting authentication. Please contact the app maintainer to resolve the issue.

`Error while trying to use the following icon from the Manifest: https://browser.blockstack.org/static/images/app-blockstack.png (Download error or resource isn't a valid image)`

It looks like problem with blockstack version. How to solve ?

**Comment by jehunter5811** [comment]
Was this when running Graphite locally or when using it at https://app.graphitedocs.com?

**Comment by mkvaghani** [comment]
@jehunter5811   while running Graphite locally

**Comment by jehunter5811** [comment]
Per the README: 

"Note: Local development will result in CORS errors on authentication. Use a CORS browser extension to get around this. Future version will eliminate this need and when pushed to a hosted site, the CORS error is resolved."
