### ISSUE TITLE
Link to /about results in 404

### ISSUE THREAD

**Issue by johnnywandering** [Graphite-Docs/graphite#168]
Hi @jehunter5811 , the link to About from the Info menu results in a 404:

https://www.graphitedocs.com/about

**Comment by jehunter5811** [comment]
Thanks for this report. Working on an updated marketing site deployment to get all additional pages back in there.

**Comment by jehunter5811** [comment]
Just updated the marketing site and all sub pages are now working again. Thanks!

**Comment by johnnywandering** [comment]
Nice one Thanks Justin!

John McGowan Managing Director john@attd.com.au
linkedin.com/in/johnjmcgowan/ www.attd.com.au

*Please consider the environment before printing this mail note.*
This communication may contain CONFIDENTIAL or copyright information of
Attribution Digital. If you are not an intended recipient, you MUST NOT
keep, forward, copy, use, save or rely on this communication, and any such
action is unauthorised and prohibited. If you have received this
communication in error, please reply to this e-mail to notify the sender of
its incorrect delivery, and then delete both it and your reply. Thank you.
