### ISSUE TITLE
ERROR in ./src/index.js Module build failed: SyntaxError: Unexpected token (11:2)   -- webpack: Failed to compile, error.

### ISSUE THREAD

**Issue by rahulremanan** [Graphite-Docs/graphite#2]
I tried compiling Graphite-Docs from source in Ubuntu 18.04, with nodejs legacy version 8 and npm package manager. I followed the install instructions from GitHub repo:

$ git clone https://github.com/Graphite-Docs/graphite
$ cd graphite
$ git checkout
$ sudo npm install
$ sudo npm run start

When I run 'npm run start' I am getting this error message: webpack failed to compile.

Any ideas on how to fix this?

--- Full console log ---

> Graphite@0.0.0 start /home/rahulremanan/graphite
> NODE_ENV=development webpack-dev-server

Project is running at http://localhost:8081/
webpack output is served from /
404s will fallback to /index.html
Hash: 68f421c2fbb264cb29dc
Version: webpack 2.7.0
Time: 10226ms
           Asset       Size  Chunks             Chunk Names
 index_bundle.js     142 kB       0  [emitted]  main
      index.html    3.76 kB          [emitted]
   manifest.json  282 bytes          [emitted]
icon-192x192.png    44.8 kB          [emitted]
chunk    {0} index_bundle.js (main) 318 kB [entry] [rendered]
    [2] ./src/index.js 644 bytes {0} [built] [failed] [1 error]
    [3] (webpack)-dev-server/client?http://localhost:8081 7.95 kB {0} [built]
    [6] ./~/events/events.js 8.33 kB {0} [built]
    [7] ./~/html-entities/index.js 231 bytes {0} [built]
   [10] ./~/loglevel/lib/loglevel.js 7.86 kB {0} [built]
   [11] ./~/punycode/punycode.js 14.7 kB {0} [built]
   [15] ./~/sockjs-client/dist/sockjs.js 181 kB {0} [built]
   [16] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [17] ./~/url/url.js 23.3 kB {0} [built]
   [18] ./~/url/util.js 314 bytes {0} [built]
   [19] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
   [20] (webpack)-dev-server/client/socket.js 1.05 kB {0} [built]
   [22] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {0} [built]
   [23] (webpack)/hot/emitter.js 77 bytes {0} [built]
   [24] multi (webpack)-dev-server/client?http://localhost:8081 ./src/index.js 40 bytes {0} [built]
     + 10 hidden modules

ERROR in ./src/index.js
Module build failed: SyntaxError: Unexpected token (11:2)

   9 |
  10 | ReactDOM.render(
> 11 |   <App />,
     |   ^
  12 |   document.getElementById('root')
  13 | );
  14 |

 @ multi (webpack)-dev-server/client?http://localhost:8081 ./src/index.js
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 545 kB [entry] [rendered]
        [0] ./~/lodash/lodash.js 540 kB {0} [built]
        [1] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 4.14 kB {0} [built]
        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
webpack: Failed to compile.

**Comment by rahulremanan** [comment]
Screenshot of the console log:
![webpack_failed_to_compile--graphite](https://user-images.githubusercontent.com/20053902/37014401-5aa39d2a-20f8-11e8-9703-f497b1fb7789.jpg)

**Comment by FranckKe** [comment]
Had the same error as well and ran into a few more:
- Install redux and react-redux
- Add babel presets in webpack (line 37)
```js 
{ test: /\.js$/, loader: 'babel-loader', exclude: /node_modules/, query: { presets:['es2015','react'] } }
```
- Change `scrollToBottom` function in `src/components/messages/SingleConversation.js` and `src/components/messages/Conversations.js`
```
// scrollToBottom = () => {
scrollToBottom() {
```
Might do a PR later

**Comment by jehunter5811** [comment]
@FranckKe We absolutely welcome pull requests! As for the issue @rahulremanan ran into, will try to replicate. We've run locally on Mac and Windows, but have not tested Ubuntu.

**Comment by rahulremanan** [comment]
Here is what worked for me: I replaced the official repo with @jehunter5811 

-- To fix missing dependencies --
$ sudo npm install --save-dev webpack
$ sudo npm install redux
$ sudo npm install file-loader

-- Install and compile Graphite Editor --
$ git clone https://github.com/jehunter5811/graphite-blockstack/
$ cd graphite
$ git checkout
$ sudo npm install
$ sudo npm run start

**Comment by FranckKe** [comment]
By looking at your repo @jehunter5811, it looks like you did not copy your hidden file when you migrated it.

**Comment by jehunter5811** [comment]
@FranckKe That is very very likely. I'll work on correcting this soon. Thanks for spotting that!

**Comment by jehunter5811** [comment]
I just committed the missing file (I think it was only the babel file). I'm going to close this issue, but if new problems arise from this same thread, we can re-open.

**Comment by FranckKe** [comment]
Awesome. You might want to add your `.gitignore` as well to prevent `node_modules` to be committed.
