### ISSUE TITLE
Sheet with no name now inaccessible 

### ISSUE THREAD

**Issue by jsparknz** [Graphite-Docs/graphite#20]
Somehow I managed to save a sheet I was working on with an empty file name. The sheet is still listed in the file listing,  but there is no way to click into it. 

![screenshot_20180606-194610_brave](https://user-images.githubusercontent.com/13808826/41024073-4f18b626-69c2-11e8-9698-b769a12eae47.jpg)

**Comment by jehunter5811** [comment]
Hey @jsparknz, that's strange! It should automatically fall back to "Untitled" if you don't enter a title. I'll do some additional testing to try to replicate and catch this. In the meantime, the quick fix to access your file is to open the developer console. You should see an array of files. Grab the file ID and then in the URL bar enter: https://app.graphitedocs.com/sheets/{fileID}.

Once the file loads up, give it a title, and you'll be all set.

**Comment by jsparknz** [comment]
Thanks @jehunter5811. I was able to get back into the sheet using the developer console to get the file ID and then use the direct URL. I was then able to give the sheet a name and all was back to normal. Weirdly though, when I returned back to the file listing, the other sheet in my file listing then had no name! I was able to recover that sheet using the same method and it hasn't happened again since. So I'm not sure what happened there! 

Thank you for your help.

Jon

**Comment by jehunter5811** [comment]
Whoa! That's super weird...

Please keep an eye on that and let me see if you see anything else like that. I rolled out improvements to sheets that hopefully mitigates the chances of this happening. I'll close the issue for now, but feel free to re-open if anything weird happens.
