### ISSUE TITLE
TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by nrydevops** [Graphite-Docs/graphite#25]
Title: TypeError: Cannot read property 'toUpperCase' of undefined
Environment: Linux Mint 19, NPM 3.5.2, Chromium Version 68.0.3440.75, 
Steps to reproduce: Add a PDF or image file to the Vault, Click to add a tag to the file, and type in a three letter tag in all CAPS. ie... ABC
Expected Result: It should have added the tag to the file
Actual Result: This has caused a major issue and now I can't even get into my Vault anymore. When I try to click on my Graphite Vault I am getting the following error:
×
TypeError: Cannot read property 'toUpperCase' of undefined
(anonymous function)
src/components/vault/VaultCollection.js:725
  722 | {
  723 |   uniqueType.map(type => {
  724 |     return (
> 725 |       <li className="filter-li" key={Math.random()}><a onClick={() => this.setState({ selectedType: type, typeList: "hide", applyFilter: true})}>{type.split('/')[1].toUpperCase()}</a></li>
  726 |     )
  727 |   })
  728 | }
View compiled
VaultCollection.render
src/components/vault/VaultCollection.js:723
  720 | {/* Type list */}
  721 |   <ul className={typeList}>
  722 |   {
> 723 |     uniqueType.map(type => {
  724 |       return (
  725 |         <li className="filter-li" key={Math.random()}><a onClick={() => this.setState({ selectedType: type, typeList: "hide", applyFilter: true})}>{type.split('/')[1].toUpperCase()}</a></li>
  726 |       )
View compiled
▶ 17 stack frames were collapsed.
(anonymous function)
src/components/vault/VaultCollection.js:144
  141 | .then((fileContents) => {
  142 |   if(fileContents){
  143 |     this.setState({ files: JSON.parse(fileContents || '{}') });
> 144 |     this.setState({filteredValue: this.state.files});
  145 |   }else {
  146 |     this.setState({ files: [] });
  147 |     this.setState({filteredValue: []});
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

Visual Proof (screenshots, videos, text): 
![typeerror](https://user-images.githubusercontent.com/39569902/43743674-d363bd56-99a4-11e8-8c15-422479b2efe4.PNG)

**Comment by jehunter5811** [comment]
Resolved in the most recent commit.
