### ISSUE TITLE
Since this is a decentralized, where are my documents stored? Am I still in control?

### ISSUE THREAD

**Issue by nathanawmk** [Graphite-Docs/graphite#26]
Since this is a decentralized, where are my documents stored? Am I still in control?

**Comment by jehunter5811** [comment]
If you chose default storage when setting up your Blockstack profile, then your files are stored on Blockstack's default Azure blob. However, those files are encrypted with your encryption key.

You can set up your own storage locations at anytime. This process will get much easier in the near future, but if you're interested in doing this now, I recommend starting here:

https://github.com/blockstack/gaia

Then, you can read through the numerous posts on the Blockstack forum about this: https://forum.blockstack.org.
