### ISSUE TITLE
Markdown support like Paper

### ISSUE THREAD

**Issue by larrysalibra** [Graphite-Docs/graphite#28]
It would be cool if graphite supported markdown like Dropbox Paper does - it works if you type it and doesn't affect you at all if you don't know it.

**Comment by jehunter5811** [comment]
Shipped :)

**Comment by larrysalibra** [comment]
yay! thanks!

**Comment by OtterKring** [comment]
It works while writing markdown directly in the editor, but Copy&Paste a prewritten markdown content does not convert automatically and I cannot uploade .md files either. Please add support for this, too. Offline prewriting in markdown and then just uploading or pasting to GD would be great.

**Comment by jehunter5811** [comment]
Love this idea. Converting this to a feature on the backlog, thanks!

**Comment by realky711** [comment]
Yep
