### ISSUE TITLE
not able to save document, JS errors

### ISSUE THREAD

**Issue by demarant** [Graphite-Docs/graphite#3]
OS: Ubuntu 17.10
Browser: Version 64.0.3282.186 (Official Build) (64-bit)

I installed blockstack and managed to log in, but not documents are saved...it says "saving" constantly.

Looking at the Chrome console I see the following JS errors:

Uncaught Error: Private key must be less than the curve order
    at new ECPair (index_bundle.js:1)
    at t.getPublicKeyFromPrivate (index_bundle.js:1)
    at t.value (index_bundle.js:1)
    at index_bundle.js:1
    at o (index_bundle.js:1)
    at index_bundle.js:1
    at e.notifyAll (index_bundle.js:1)
    at r.close (index_bundle.js:1)
    at r.closeAll (index_bundle.js:1)
    at r.perform (index_bundle.js:1)
    at a (index_bundle.js:1)
    at r.perform (index_bundle.js:1)
    at Object.batchedUpdates (index_bundle.js:1)
    at Object.batchedUpdates (index_bundle.js:1)
    at Object._renderNewRootComponent (index_bundle.js:1)
    at Object._renderSubtreeIntoContainer (index_bundle.js:1)
documents:1 

![graphite](https://user-images.githubusercontent.com/320440/37049427-23e19156-2171-11e8-8bc2-7b21135c433c.png)

not sure if the above is related to the issue that no documents are saved.

**Comment by jehunter5811** [comment]
@demarant Is this while running locally or while accessing the app at app.graphitedocs.com?

**Comment by demarant** [comment]
@jehunter5811 it is while accessing the app at app.graphitedocs.com

**Comment by jehunter5811** [comment]
@demarant That's not good! In your console screenshot, you see that Object toward the top? Can you expand that and see if there is an appPrivateKey present? Don't send a screenshot of that since, you know, it's a private key. But my guess is something is preventing that key from being generated. But I want to confirm.

**Comment by demarant** [comment]
@jehunter5811 

yes there is an appPrivateKey:

![graphite-docs-save-issue](https://user-images.githubusercontent.com/320440/37149473-622d3402-22ce-11e8-8e46-d1446f8e741b.png)

if you need other debug info, just let me know

**Comment by jehunter5811** [comment]
Thanks for this. I'm trying to get a sense of what browser you're using from that screenshot. It looks like Firefox, but the inspector on top looks like Chrome's. Can you tell me?

**Comment by demarant** [comment]
It was in the issue description already :D

OS: Ubuntu 17.10
Browser: Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by demarant** [comment]
I would like to add additional info that may help.

For me the experience is as following:

In Chrome i open app.graphitedocs.com
When I click sign in with Blockstack it open a dialogue box where it suggest to open link with Blockstack browser (which I previously installed following official documentation for Ubuntu). I login and from there I was redirected to app.graphitedocs.com. But once logged in, I never managed to save a document and therefore I looked at the js console. 

In Firefox it is not possible to login at all, because when clicking the sign in with Blockstack it opens a dialog box but without the option to open with Blockstack browser. I am a bit confused on how this Blockstack works.... I guess it is quite early in development.

Hopes this helps.

**Comment by jehunter5811** [comment]
@demarant This is really helpful. I assume you are on the most recent version of the Blockstack Browser, but you might just want to try downloading again from [here](https://blockstack.org/install). 

In Firefox, what does that dialog boxy say?

**Comment by demarant** [comment]
@jehunter5811 

sorry, my mistake, it is in Chrome that I get the login dialog box saying "Open xdg-open, see below
![graphite-docs-login-issue-chrome](https://user-images.githubusercontent.com/320440/37178236-3774b826-2322-11e8-9185-51fe27f8ff65.png)
In firefox, when I log in I get the dialog box with the proper association label "Blockstack browser". 

now when I confirm, it opens another chrome window pointing to http://localhost:8888, my local blockstack browser server I guess, but the page is now blank and cannot authenticate there. I would expect an error message on that page instead of just a blank page.

I did install blockstack browser via the shell script provided at https://blockstack.org/install

I can try to uninstall blockstack browser and install again, starting with Chrome. Maybe it got messed up as in my first attempt to login to the graphitedocs, I didn't have blockstack browser installed.

**Comment by jehunter5811** [comment]
Give that a shot and let me know if that works. If it doesn't we may need to open an issue with Blockstack. I think the fact that your Chrome dialog has the wrong text and that it opens to a blank page is an issue Blockstack will want to know about as well. Their issues for browser related items can be opened [here](https://github.com/blockstack/blockstack.js/issues).

**Comment by jehunter5811** [comment]
This appears to be a Blockstack specific issue if an issue still exists. Closing for now. Feel free to open if there is more info.
