### ISSUE TITLE
Errors in browser console that complain about missing files.

### ISSUE THREAD

**Issue by clydedacruz** [Graphite-Docs/graphite#33]
Keep seeing these errors in by browser console when using graphite 

![graphite_errors](https://user-images.githubusercontent.com/10458762/45669484-dd992300-bb3d-11e8-81b1-e7358ea33a62.png)

**Comment by jehunter5811** [comment]
Hi @clydedacruz, Those errors are just telling you that those files do not yet exist. When you access any page in Graphite that might need to make use of data from those files (the dashboard for example), an api call is made to fetch the file(s). 

In your specific case, you have not created any spreadsheets, you have not added any Contacts, you have not uploaded any files, and you have not set up any integrations. The other errors are checks that run to determine if a user is a Graphite Pro member or not.
