### ISSUE TITLE
Install issue: Bower Deprecated (Raspbian - fully updated)

### ISSUE THREAD

**Issue by zeHamish** [Graphite-Docs/graphite#35]
i'm surprised to not see this in the issues list already.

would liked to have used the community brains trust to resolve.

virgin os, fully patched up, raspberry pi3 on debian

**gets:**
root@base:/home/pi/graphite# npm install
(node:6434) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
npm WARN deprecated react-handsontable@0.3.2: Handsontable for React is now available as @handsontable/react.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.14.69-v7+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pi/graphite
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pi/graphite/npm-debug.log
npm ERR! not ok code 0

**Comment by jehunter5811** [comment]
From doing a little research, the issue you're having appears to be from using an outdated version of npm. The bower dependency (which is not actually a dependency, but a relic from past builds) is not blocking your install. Please see this link as an example of the error you are seeing: 

https://github.com/npm/npm/issues/20896
