### ISSUE TITLE
Authentication infinite loop

### ISSUE THREAD

**Issue by rahulremanan** [Graphite-Docs/graphite#4]
I installed Graphite and managed to run successfully. Now, I have issues with login. 
I setup blockstack in Ubuntu 18.04 using the official install instructions. 

Step 1: Download the official blockstack binary:
wget https://github.com/blockstack/blockstack-browser/releases/download/v0.25.0/Blockstack-for-Linux-v0.25.0.sh

Step 2: Run the installer

$ chmod a+x ./Blockstack-for-Linux-v0.25.0.sh
$ ./Blockstack-for-Linux-v0.25.0.sh pull
$ ./Blockstack-for-Linux-v0.25.0.sh start

Step 3: Setup blockstack CoreAPI:

I followed the instructions to setup an account.

{Note: The docker container and the on-screen instructions to enter CoreAPI password exposes the password as plain-text. I don't why it should be doing that, since the whole premise is to create a secure mechanism of collaboration?!}

Once the blockstack docker is running, I launched Firefox and launched the local instance of Graphite, running at localhost:8080.
It takes me to the login page, but I am stuck in an infinite loop. The app never successfully authenticates via blockstack.

Any thoughts on how to fix this?

**Comment by jehunter5811** [comment]
@rahulremanan Can you check console when authentication is trying to complete and tell me what you see? 

Regarding the CoreAPI password in plain text, you may want to jump onto the [BlockstackJS](https://github.com/blockstack/blockstack.js) repo and report that.

**Comment by jehunter5811** [comment]
No response, closing issue.
