### ISSUE TITLE
Document Not Saved

### ISSUE THREAD

**Issue by shane1900** [Graphite-Docs/graphite#6]
Not sure how to repeat this but spent an hour on a document and it was not saved.  The next time I went there it was blank.

Using Safari on Mac.  

Separate issue, safari often show's a blank page after a certain amount of time, just all white.

**Comment by jehunter5811** [comment]
Hi @shane1900, I'm sorry to hear that! Documents autosave every time there's a change made, so let's try a couple things to see if the document is actually stored somewhere for you. 

First, what do you see when you go to the Documents page? Do you see an endless loading bar?

**Comment by jehunter5811** [comment]
Hi @shane1900, 

Have you been able to test this?

**Comment by shane1900** [comment]
Hi there.  When I went to the document I just saw a blank document.  No loading bar or anything unusual.  I'm not worried about losing the document anymore so I will try to track more details if it were to happen again.

**Comment by jehunter5811** [comment]
Thanks, @shane1900. I'll close this issue for now. Enjoy!
