### ISSUE TITLE
Confusing 'bump' when copy-pasting

### ISSUE THREAD

**Issue by abonnementer** [Graphite-Docs/graphite#60]
Hi Graphite Docs

I've been using your web-app for a few days and experienced one important bug:
When I press Ctrl. + V the window jumps around once and you loose orientation editing a document. I have experienced this error once before editing a site, when I was using an older CMS-system.

Looking foreward to advocate Graphite and see it gradually progress in quality.

Kind regards,
Niels, a non-techie that just joined Github to file feature requests and follow Graphite.

**Comment by jehunter5811** [comment]
Sincerely appreciate you filing this bug, Niels! We'll figure it out.

**Comment by jehunter5811** [comment]
Here's is the thread that fixes the issue: https://github.com/quilljs/quill/issues/1374#issuecomment-407888147

In testing now before production release.

**Comment by jehunter5811** [comment]
This bug is now resolved. On paste, your position is held. Future enhancement will likely be to scroll to the bottom of the document after page, but for now, this just fixes the issue where you'd scroll back to the TOP after paste.
