### ISSUE TITLE
Missing documents

### ISSUE THREAD

**Issue by abonnementer** [Graphite-Docs/graphite#69]
It seems my list of documents are not including all documents. The missing documents do not occur when I search them.

**Comment by jehunter5811** [comment]
@abonnementer I'll need a lot more information to help you with this. Can you please follow this guide: https://github.com/Graphite-Docs/graphite#report-bugs 

It would be helpful if you include screenshots for reference as well.

**Comment by jehunter5811** [comment]
Closing until more info provided.
