### ISSUE TITLE
bug:Why cannot I login using blockstack id 

### ISSUE THREAD

**Issue by salamsoliman** [Graphite-Docs/graphite#7]
I clicked https://app.graphitedocs.com/ and the sign in with blockstack id, then I open the blockstack,and As mentioned ,I selected my blockstack id,and clicked approve ,but error showed "Invalid Sign In Request" .
![2018-03-24 5 03 33](https://user-images.githubusercontent.com/12605959/37853286-efd30a58-2f20-11e8-9574-6c8d0a311850.png)

**Comment by jehunter5811** [comment]
Hi @salamsoliman, 

Based on the auth screen in your screenshot, you are using an outdated version of the Blockstack Browser. Please download the most recent version, and you should be all set.

**Comment by salamsoliman** [comment]
gota,I would try it now.
