### ISSUE TITLE
Changes to gitignored files are tracked by Git

### ISSUE THREAD

**Issue by arisgk** [Graphite-Docs/graphite#73]
### Environment

**OS:** Ubuntu 18.04.1 LTS

### Steps to reproduce

1. Update your `.env` file in project root (which is gitignored)
2. Run `git status` to see if the change was tracked by git

### Expected result

Changes to `.env` (or any other gitignored files) should be ignored

### Actual result

Change to `.env` is not ignored

### Potential solution

According to [the answer with the most upvotes in this question](https://stackoverflow.com/questions/11451535/gitignore-is-not-working), something like:

```
git rm -r --cached .
git add .
git commit -m "Fixes untracked files"
```

will fix the issue

**Comment by jehunter5811** [comment]
Thanks, @arisgk! Not sure how long it would have taken me to track this down, so I appreciate the link. Just followed the steps outlined.
