### ISSUE TITLE
To test blockstackgraphite ,I try to install it in my local mac, and I met some error on npm install 

### ISSUE THREAD

**Issue by salamsoliman** [Graphite-Docs/graphite#9]
I followed this tutorial:https://github.com/Graphite-Docs/graphite
And I typed commands in my macos terminal as follows:
`git clone git@github.com:Graphite-Docs/graphite.git`
`npm install`
`https://github.com/Graphite-Docs/graphite`

Here are the screenshot.How to fix it ?

![2018-04-06 6 04 35](https://user-images.githubusercontent.com/12605959/38415776-1d509c1c-39c5-11e8-9346-d81754d6ad32.png)
![2018-04-06 6 04 53](https://user-images.githubusercontent.com/12605959/38415778-1d9e531c-39c5-11e8-8798-df43346e70af.png)

**Comment by artusvranken** [comment]
You should first `cd` into the cloned directory:

```shell
git clone https://github.com/Graphite-Docs/graphite.git
cd graphite
npm install
npm start
```

These commands should work (if the build passed)

**Comment by jehunter5811** [comment]
Sorry about that. Should get the README instructions updated to specify that you'll need to cd into the project directory.
